language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Ho me
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIAY4FSMIK4DZWZ3TEI
    secret_access_key: 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
    bucket: helpcs
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시  메일로 알람
notifications:
  email:
    recipients:
      - smjsih@naver.com